[package]
name = "code_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
egui = "0.27"
rfd = "0.14"
syntect = { version = "5.3", default-features = false, features = ["default-syntaxes", "regex-onig"] }
vscode-theme-syntect = "0.1.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
